### ISSUE TITLE
DllNotFoundException: libpocketsphinxwrap)

### ISSUE THREAD

**Issue by kiookey** [cmusphinx/pocketsphinx-unity-demo#1]
Hi nshmyrev, I got a error when I run this demo. 
DllNotFoundException: libpocketsphinxwrap

Please tell me how to fix this problem, I am very interested in this project.
Thank you!

**Comment by nshmyrev** [comment]
You need to compile dll for your platform. Linux example is in pocketsphinx/swig/charp. Sources come with precompiled OSX dll.
