### ISSUE TITLE
on Android doesn't work

### ISSUE THREAD

**Issue by Vemnym** [cmusphinx/pocketsphinx-unity-demo#3]
DllNotFoundException: libpocketsphinxwrap
Pocketsphinx.pocketsphinxPINVOKE+SWIGExceptionHelper..cctor () (at Assets/Pocketsphinx/pocketsphinxPINVOKE.cs:105)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for SWIGExceptionHelper
Pocketsphinx.pocketsphinxPINVOKE..cctor () (at Assets/Pocketsphinx/pocketsphinxPINVOKE.cs:125)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Pocketsphinx.pocketsphinxPINVOKE
Pocketsphinx.Decoder.DefaultConfig () (at Assets/Pocketsphinx/Decoder.cs:83)
TestScript.SetupDecoder () (at Assets/TestScript.cs:40)
TestScript.Start () (at Assets/TestScript.cs:25)

**Comment by nshmyrev** [comment]
Only osx is supported

**Comment by Vemnym** [comment]
Why then is it here? in TestScript.cs

else if (Application.platform == RuntimePlatform.Android) {
			c.SetString ("-hmm", "/sdcard/Android/data/edu.cmu.sphinx.pocketsphinx/files/sync/en-us-ptm");
			c.SetString ("-dict", "/sdcard/Android/data/edu.cmu.sphinx.pocketsphinx/files/sync/cmudict-en-us.dict");

**Comment by nshmyrev** [comment]
It is an artefact from the distant future.
