### ISSUE TITLE
Update documentation please.

### ISSUE THREAD

**Issue by TriflesGames** [cmusphinx/pocketsphinx-unity-demo#4]
<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/12006939/27114200-9c5f3340-50ca-11e7-9e19-8047c6fe496b.png">

Hi,
What should i do ? Thanks.

**Comment by nshmyrev** [comment]
Install pocketsphinx

**Comment by ayushvora** [comment]
Well, I ran `brew install cmu-pocketsphinx` on my Mac. What else?

**Comment by nshmyrev** [comment]
> Well, I ran brew install cmu-pocketsphinx on my Mac. What else?

You need to install from source in /usr/local folder, that is what it is saying.

**Comment by ayushvora** [comment]
Thanks, Nickolay, it works after installing from source.

Side-note for anyone wondering - "installing a project from source" means downloading that project's source code (from github or any other reliable source) and following the instructions that project's README says for building the project. "Building" a project is a standard software development term - often involving running some commands on the command-line prompt. `make` is one such command.
