### ISSUE TITLE
[Repo feature request] Make it easier to access libraries for various platforms

### ISSUE THREAD

**Issue by Naphier** [cmusphinx/pocketsphinx-unity-demo#5]
There's nothing like finding an interesting project then finding out just to try it you need to spend a bunch of extra time just making libraries. Please consider including built libraries for the most common platforms for Unity such as Windows and Android. It would definitely improve the number of people using this project by simplifying on-boarding.
Thanks!

**Comment by DrewRidley** [comment]
Hello! Just to clarify, they actually do have the libraries precompiled avaliable on their website. The only issue is that I am unsure as to whether the file "pocketsphinx.dll" is identical to "sphinxwrap.dll". I do not know whether they modify it in any way.

**Comment by lucasgaspar** [comment]
Where I can find those libraries?

**Comment by Naphier** [comment]
Good luck

**Comment by nshmyrev** [comment]
I shared

https://alphacephei.com/kaldi/PsTest.zip

All dlls are inside. I was planning to publish a Unity plugin some time ago, but the paperwork for that made me bored.

**Comment by lucasgaspar** [comment]
Thank youuu! 😄
