### ISSUE TITLE
[Repo feature request] Updated readme with links to precompiled libraries. 

### ISSUE THREAD

**Issue by Funnyguy77** [cmusphinx/pocketsphinx-unity-demo#8]
First, thank you for your work in creating PocketSphinx. It's really a great tool.

However, I would really like to see an easier on-boarding process for new users (like myself). Sadly the current project pushed to this repo only works for OSX. But as mentioned in another GitHub issue, there are precompiled libraries and a working Windows project at this url - [https://alphacephei.com/kaldi/PsTest.zip](https://alphacephei.com/kaldi/PsTest.zip)

Could you please update the readme (or main branch) to include these libraries? I spent quite a long time attempting to compile a library on my own, only to later find out the work was done for me. I'm sure you can also see the value in having an easier on-boarding process.

**Comment by nshmyrev** [comment]
Let it be like before for now, I'll probably update later. Actually we have much better recognizer in  kaldi-android-demo these days, works perfectly on Unity too.
