### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by jin-archipin** [cmusphinx/pocketsphinx-unity-demo#9]
First of all, thank you for your work. I'm really excited to make this work in latest version of unity(2019.3) on windows. I saw I have to make dll for my own for windows.
You said I have see pocketsphinx/swig/csharp/, and I found the makefile, but I still don't know what's going on....
can you give me a little bit of detail what should I do?
Thanks in advance.

**Comment by Funnyguy77** [comment]
Hi! I know this is a very late response, but hopefully this will be of some help. I've actually written an example for Windows, OSX, iOS, & Android! 

https://github.com/Funnyguy77/PocketSphinxUnityDemo

**Comment by nshmyrev** [comment]
Very good!

**Comment by jin-archipin** [comment]
> Hi! I know this is a very late response, but hopefully this will be of some help. I've actually written an example for Windows, OSX, iOS, & Android!
> 
> https://github.com/Funnyguy77/PocketSphinxUnityDemo

That's actually super awesome! I can't wait to run the demo!
Thank you so much
